name: Acceptances tests

on:
  pull_request_target:
    branches:
      - master
  workflow_dispatch:
    

jobs:
  Acceptances_tests:
    concurrency: terraform-acceptance-test
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build go test
        run: make test
#      - name: Run acceptance tests
#        run: make test #acc
        env:
          OUTSCALE_ACCESSKEYID: ${{ secrets.OSC_ACCESS_KEY }}
          OUTSCALE_SECRETKEYID: ${{ secrets.OSC_SECRET_KEY }}
          OUTSCALE_REGION: ${{ secrets.OSC_REGION }}
          OUTSCALE_ACCOUNT: ${{ secrets.OSC_ACCOUNT_ID }}
          OUTSCALE_IMAGEID: ${{ secrets.OUTSCALE_IMAGEID }}
