name: Integration tests

on:
  pull_request_target:
    branches:
      - master
  workflow_dispatch:
    

jobs:
  Integration_tests:
    #concurrency: terraform-integration-tests
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.5.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Build go test
        run: make test
      - name: Run integration tests
        run: make test-integration
        env:
          OUTSCALE_ACCESSKEYID: ${{ secrets.OSC_ACCESS_KEY }}
          OUTSCALE_SECRETKEYID: ${{ secrets.OSC_SECRET_KEY }}
          OUTSCALE_REGION: ${{ secrets.OSC_REGION }}
          OUTSCALE_ACCOUNT: ${{ secrets.OSC_ACCOUNT_ID }}
          OUTSCALE_IMAGEID: ${{ secrets.OUTSCALE_IMAGEID }}
