name: Test_ci

on:
  push:
    branches: [ ci-test ]
  pull_request:
    branches: [ master ]

jobs:
  Acceptances_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build go format
      run: make fmt
    - name: Build go test
      run: make test
    - name: Run acceptance tests
      run: make testacc
      env:
        OUTSCALE_ACCESSKEYID: ${{ secrets.OUTSCALE_ACCESSKEYID }}
        OUTSCALE_SECRETKEYID: ${{ secrets.OUTSCALE_SECRETKEYID }}
        OUTSCALE_REGION: ${{ secrets.OUTSCALE_REGION }}
        OUTSCALE_ACCOUNT: ${{ secrets.OUTSCALE_ACCOUNT }}
        OUTSCALE_IMAGEID: ${{ secrets.OUTSCALE_IMAGEID }}
